[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/manifest.json"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET"
Access-Control-Allow-Headers = "X-Requested-With, content-type, Authorization"

[build]
  NODE_OPTIONS = "--max-old-space-size=4096"
