name: Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

env:
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: xxxx
  NEXT_PUBLIC_QUIKNODE_URL: xxxx
  NEXT_PUBLIC_ALCHEMY_MAINNET_API_KEY: xxxx
  HARDHAT_RPC_URL: ${{ secrets.HARDHAT_RPC_URL }}

jobs:
  linting:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  build:
    name: Next Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run build
        run: CI=true pnpm build
